# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# https://fabricmc.net/develop/
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.15.6

# Mod Properties
mod_version=1.0.0
maven_group=com.subtick
archives_base_name=subtick-input-engine

# Dependencies
fabric_version=0.100.8+1.21
